### ISSUE TITLE
jekyll-archives interferes with -i (incremental build)

### ISSUE THREAD

**Issue by feuerbach** [jekyll/jekyll-archives#103]
Hi,

First of all, thanks for the great plugin.

I found that when doing normal builds, the plugin doesn't really slow down the build — with or without the plugin, the build takes about 5.7 seconds. (I only generate tag pages, about 10 of them.)

However, the incremental build used to take about 0.3 seconds, but when jekyll-archives is enabled, it takes the full 5.7 seconds. This is even true if I set `enabled: []`, i.e. when no work needs to be done.

Can this be fixed?

**Comment by DirtyF** [comment]
@feuerbach how did you enable incremental (config or option on the command line?). I don't experiment this with archive layouts for years and month.

**Comment by DirtyF** [comment]
@feuerbach could you test with #123 by specifying GitHub branch in your `_config.yml`:

```ruby
gem "jekyll-archives", git: "https://github.com/bliof/jekyll-archives", branch: "refactor-base"
```

**Comment by feuerbach** [comment]
Hi @DirtyF,

I enable it with `-i`. Will try that branch.

**Comment by DirtyF** [comment]
@feuerbach OK, I enabled it with `incremental:true` in a `_config_local.yml`

**Comment by feuerbach** [comment]
Hmm, I can no longer reproduce this even with 8d06b62920f83a1bc3e008cc2093113a1431fa66.

I don't know what to think of this, tbh. I did update jekyll since and even made a couple of local changes, so they might have something to do with this.

I guess feel free to close this, and I'll reopen if I run into this again.
