### ISSUE TITLE
Support for Custom Collections

### ISSUE THREAD

**Issue by zoltron2001** [jekyll/jekyll-archives#109]
It seems [site.posts is hardcoded](https://github.com/jekyll/jekyll-archives/blob/815e72b60a7e1f687dba18276ad64639d3b24017/lib/jekyll-archives.rb#L34) into the gem. Please provide support for custom collections via configuration.

For example, we have one site that has a "works" collection. Why not just put works in a posts directory, you might ask. Well, then we'd be limited to using jekyll-archives for one collection per website.

**Comment by DirtyF** [comment]
see #88
