### ISSUE TITLE
This plugin does not work in github

### ISSUE THREAD

**Issue by rhatyang** [jekyll/jekyll-archives#112]
I can use this plugin locally to create an archive folder. Why is it that I can not generate a folder when it is pushed to github?

**Comment by DirtyF** [comment]
GitHub Pages runs Jekyll in safe mode for security reasons and only allows a bunch of [white-listed plugins](https://pages.github.com/versions/).

Alternately you can build your site and push it to GitHub on your GitHub Pages branch, configure Travis CI to do this for you, or link your GitHub repository and host your website on [Netlify](https://netlify.com) for instance.
