### ISSUE TITLE
Gem won't install on windows when added to group :jekyll_plugins

### ISSUE THREAD

**Issue by looeee** [jekyll/jekyll-archives#119]
If my gemfile has:

```
group :jekyll_plugins do
  gem 'jekyll-archives'
  gem "jekyll-last-modified-at"
  gem "jekyll-livereload"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jemoji"
end
```
and I run "bundle" I get the error: `Could not find gem 'jekyll-archive x64-mingw32' in any of the gem sources listed`

However if I change it to:

```
gem 'jekyll-archives'

group :jekyll_plugins do
  gem "jekyll-last-modified-at"
  gem "jekyll-livereload"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jemoji"
end
```

Then it works fine.

**Comment by looeee** [comment]
Also, now that it _has_ installed, moving it in or out of the group has not effect - the error only happened when it was not previously installed.

**Comment by DirtyF** [comment]
Thanks for the feedback, `jekyll-archive x64-mingw32` clearly isn't a gem name, so it might be a Jekyll issue on Windows (works fine on macOS).

**Comment by looeee** [comment]
I'm pretty sure that `x64-mingw32` is the value of `RUBY_PLATFORM` on my version of ruby / windows - that is Ruby 2.3.3 and windows 10. 

This is is the first time I've come across this error though, and I added plenty of other gems without seeing it before. In fact I added `jekyll-last-modified-at` to the group just a couple of hours ago and it installed without problems.

**Comment by chhh** [comment]
Maybe the problem is in plural vs singular? _jekyll-archive x64-mingw32_ should actually be _jekyll-archive`s` x64-mingw32_ ?

**Comment by pathawks** [comment]
This hasn’t been reproduced, so for now it seems we can chalk it up to ghosts in the machine.
