### ISSUE TITLE
Layout documentation needs better escaping

### ISSUE THREAD

**Issue by kornysietsma** [jekyll/jekyll-archives#141]
The documentation in https://github.com/jekyll/jekyll-archives/blob/master/docs/layouts.md has no escaping of liquid tags.

This leads to very confusing output on the page at https://jekyll.github.io/jekyll-archives/layouts/ where sample layouts look like:

```
<h1>Archive of posts with  'Layouts'</h1>
<ul class="posts">
  
</ul>
```

instead of having the actual liquid tags needed.

**Comment by ashmaroli** [comment]
Thank you for reporting this @kornysietsma
