### ISSUE TITLE
Documentation not clear for beginners

### ISSUE THREAD

**Issue by yveshema** [jekyll/jekyll-archives#147]
I tried to use this plug-in for my site but I must be missing something because I couldn't get it to work.
I spent hours searching the internet for answers all in vain. 
A tutorial or full example for at least one archive type, say category-archive, would be appreciated.

**Comment by yveshema** [comment]
I turns out my problem had to do with the fact that Github pages doesn't support this plug-in. 
This is unfortunate, because from what I have read so far, jekyll-archives is a great time saver.
For now, I will go with this solution: http://mrloh.se/2015/06/automatic-archives-for-jekyll-on-github-pages/

**Comment by ashmaroli** [comment]
You can **try** leaving a request to have this plugin whitelisted for GitHub Pages by opening a ticket at the [gem's repo](https://github.com/github/pages-gem) **and** by sending a request to [GitHub Support](https://support.github.com/)
