### ISSUE TITLE
turn off when serving ?

### ISSUE THREAD

**Issue by maxandersen** [jekyll/jekyll-archives#148]
archive generation takes quite some time for our site; without it ~1-2seconds with it 7-10seconds.

any way to have archive generation turned off when rendering in serve mode ?

**Comment by ashmaroli** [comment]
You can use a second config file to disable the plugin when you are serving. For example, in
`_config_dev.yml`:
```yaml
jekyll-archives:
  enabled: false
```
Then run:
```
bundle exec jekyll serve --config _config.yml,_config_dev.yml
```

**Comment by maxandersen** [comment]
that’s a nice trick - thanks!
