### ISSUE TITLE
page.title not a string

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-archives#20]
My Jekyll templates use `page.title` if it is available for the title of the HTML page.

```html
<title>{{ page.title | textilize | strip_html }}</title>
```

In pages generated by this plugin, `page.title` is available, but seems not to be a string. When I try to generate my site, I get this error:

```
      Generating... 
  Liquid Exception: no implicit conversion of Date into String in _layouts/archive_index.html
jekyll 2.4.0 | Error:  no implicit conversion of Date into String
```

**Comment by paulrobertlloyd** [comment]
I would like to be able to configure page titles in the config (the last option suggested by @nitoyon looks good). Currently I have to do give my templates a name field in the YAML, and then test for those values to see if should use `page.title` or `page.date`. I may put all this logic in one include, but still seems like more hassle than reasonably necessary.

**Comment by hazzik** [comment]
Are there any plans to implement titles function as discribed at https://github.com/jekyll/jekyll-archives/issues/20#issuecomment-58798794 ?

**Comment by alfredxing** [comment]
@hazzik Probably not. It'll just make everything even more confusing, and since the plugin already offers you the choice of layouts for each archive type, there's no loss of functionality.

**Comment by hazzik** [comment]
@alfredxing layouts is not an options, as for example, I use page.title in a title tag in default layout (or even in _includes/head.html), so, basically it means that I have to write a standalone layout for each tag because of only one line. That's so annoying

**Comment by opattison** [comment]
@hazzik One other option you have is to use conditional Liquid (`if` or `unless` statements) in your default template instead of writing new templates.
