### ISSUE TITLE
Not working on Github

### ISSUE THREAD

**Issue by dblock** [jekyll/jekyll-archives#29]
I must be doing something wrong. Works locally, but doesn't generate anything on Github.

eg. http://code.dblock.org/tag/teams

My code here: https://github.com/dblock/code, here's [the commit](https://github.com/dblock/code/commit/54abba657630977fd016401be91430a48eb659c2) in which I added jekyll-archives.

**Comment by dblock** [comment]
Whooops, found https://github.com/github/pages-gem/issues/93 :(

**Comment by alfredxing** [comment]
@dblock Yep, it's still in consideration for inclusion in Pages.

**Comment by MrLoh** [comment]
I have a GitHub Pages compatible completley automated date and tag archive solution. It works with creating files locally with a ruby script. Have a look at my blog: http://mrloh.se/2015/06/automatic-archives-for-jekyll-on-github-pages/

**Comment by alfredxing** [comment]
@MrLoh That seems like a very interesting solution! I'd encourage you to make a post in our discussion board, [talk.jekyllrb.com](https://talk.jekyllrb.com/) if you haven't done so already, so it isn't tied to an issue here where it won't likely gain a lot of exposure or discussion.

**Comment by MrLoh** [comment]
@alfredxing Thanks for the hint. I didn't know about the discussion board — pretty new to the Jekyll community.
