### ISSUE TITLE
Link to archives

### ISSUE THREAD

**Issue by yous** [jekyll/jekyll-archives#35]
I recently refreshed my blog with Jekyll, and [enabled 'jekyll-archives'](https://github.com/yous/yous.github.io/commit/01295b40b09c9f3f1644bb2fe044628ac97a3925) to generate `/categories/:name/`. But, soon, I recognized there is no way to link categories from blog index. I set multiple categories for few posts, so I have to convert an array of category to `<a>` tags joined by `', '`. First, I thought about the possibility using `{{ post.categories | map: ... | join: ', ' }}`. But `map` in Liquid is just accessing to attribute of each item of an array. So I decided to make a filter for this.

I just write `category_links` and `category_link` for jekyll-archives, as you can see in [this commit](https://github.com/yous/yous.github.io/commit/d03469750dc6ef639111550829bd1d5150f03045).
``` ruby
module Jekyll
  module Archives
    module ArchiveLinkFilters
      def category_links(categories)
        categories.map { |c| category_link(c) }.join(', ')
      end

      def category_link(category)
        site = @context.registers[:site]
        template = site.config['jekyll-archives']['permalinks']['category']
        url = URL.new({
          template: template,
          placeholders: { name: Utils.slugify(category) }
        }).to_s

        "<a href=\"#{site.baseurl}#{url}\">#{category}</a>"
      end
    end
  end
end

Liquid::Template.register_filter(Jekyll::Archives::ArchiveLinkFilters)
```

Indeed, I don't want to put extra files in `_plugins` directory. So I became curious whether this feature can be acccomplished by jekyll-archives gem or not. How do you think about making additional filters?

**Comment by alfredxing** [comment]
I believe you can access all of the archives via the `site.archives` Liquid variable?

So does something like this work for you?
```liquid
{% for archive in site.archives %}
  {% if archive.type == "category" %}
    <a href="{{ archive.url }}">{{ archive.title }}</a>
  {% endif %}
{% endfor %}
```

**Comment by yous** [comment]
Oh, I didn't know about `site.archives`. I wanted to show the categories of each post, so I had to use nested for loop:

``` liquid
{% if post.categories %}
  {% for category in post.categories %}
    {% assign no_comma = forloop.last %}
    {% for archive in site.archives %}
      {% if archive.type == "category" and archive.title == category %}
        <a href="{{ archive.url }}">{{ archive.title }}</a>{% unless no_comma %},{% endunless %}
      {% endif %}
    {% endfor %}
  {% endfor %}
{% endif %}
```

Note that I want to separate each category using comma, since I have some categories including spaces. Thanks for your notice! Feel free to close this.
