### ISSUE TITLE
`site.archives` are not generated on first build with Jekyll v3.0.0.beta2

### ISSUE THREAD

**Issue by yous** [jekyll/jekyll-archives#37]
I'm using `_includes/category_links.html` from #35:
``` liquid
{% if post.categories %}
  {% assign categories = post.categories %}
{% elsif page.categories %}
  {% assign categories = page.categories %}
{% endif %}
{% for category in categories %}
  {% assign no_comma = forloop.last %}
  {% for archive in site.archives %}
    {% if archive.type == "category" and archive.title == category %}
      <a href="{{ archive.url | prepend: site.baseurl }}">{{ archive.title }}</a>{% unless no_comma %},{% endunless %}
    {% endif %}
  {% endfor %}
{% endfor %}
```

I have `index.html` and `archives/index.html` which have `{% include category_links.html %}` and they work well with Jekyll v3.0.0.beta2. But `_layouts/category_archives.html` which is the layout of `jekyll-archives` configured in `_config.yml` won't have `site.archives`. So only I got is `•` after the title of post.

![screenshot 2015-03-06 17 59 33](https://cloud.githubusercontent.com/assets/853977/6522643/937b2a74-c42a-11e4-986f-312f9774d00e.png)

If I change `_includes/category_links.html` some times, Jekyll regenerates pages and then it shows categories properly.

![screenshot 2015-03-06 18 01 08](https://cloud.githubusercontent.com/assets/853977/6522668/ce3bf0c6-c42a-11e4-92f1-aa6d45a966d9.png)

But right after `jekyll clean` I should regenerates several times again.

**Comment by alfredxing** [comment]
Hmm... What happens when you `jekyll clean` then `jekyll build --full-rebuild`?

**Comment by yous** [comment]
It gives me the same result.

**Comment by yous** [comment]
FYI, you can see the my current source at yous/yous.github.io@8cd24a049ea92cb80d2397726d97e6f1829ea28b. Note that I use [jekyll-compress-html](https://github.com/penibelst/jekyll-compress-html), but it doesn't seem to affect this problem.

**Comment by yous** [comment]
The same problem still occurs with Jekyll v3.0.0.pre.beta5.

**Comment by yous** [comment]
It seems that `@site['archives']` or `site_payload['site']['archives']` is `nil` right before `do_layout(payload, layouts)` on `render` in `lib/jekyll-archives/archive.rb`.

**Comment by yous** [comment]
Ah, actually I was rendering `category_archives.html` with:

``` html
...
{% for post in page.posts %}
  <li>
    <span class="post-meta">
      {{ post.date }}
      {% if post.categories %}{% include category_links.html %}{% endif %}
    </span>
    ...
  </li>
{% endfor %}
...
```

And the content of `category_links.html` was:

``` html
{% if post.categories %}
  {% assign categories = post.categories %}
{% elsif page.categories %}
  {% assign categories = page.categories %}
{% endif %}
{% for category in categories %}
  ...
{% endfor %}
```

Since `category_links.html` doesn't have the context of `page` of `category_archives.html`, categories aren't displayed. I fixed this by changing `{% include category_links.html %}` to `{% include category_links.html categories=post.categories %}` and updating `category_links.html` properly.

Sorry for confusing. Now closing.
