### ISSUE TITLE
jekyll-3.0.0.pre.beta8 conflicts 

### ISSUE THREAD

**Issue by mmistakes** [jekyll/jekyll-archives#44]
Tried to fire up the latest Jekyll beta to test and get the following error on `jekyll build`.

```
Configuration file: /_config.yml
/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate jekyll-archives-2.0.0, because jekyll-3.0.0.pre.beta8 conflicts with jekyll (~> 2.4) (Gem::LoadError)
```

**Comment by pathawks** [comment]
Isn’t this just a problem with the `jekyll-archives` gem’s dependancy?

**Comment by pathawks** [comment]
Why post twice? This is the same as #45

**Comment by mmistakes** [comment]
I assumed they were different types of errors... one was from installing the gem the other when running `jekyll build` or `jekyll serve`. They likely have the same route cause but I wasn't sure so I submitted 2 issues.

**Comment by alfredxing** [comment]
I'm considering perhaps rewriting the plugin a bit, since 3.0 adds a hooks feature which may become quite useful. Thanks for the heads-up!

**Comment by mmistakes** [comment]
Works now with the 3.0 compatibility fix. Thanks!
