### ISSUE TITLE
archive pages not showing up in sitemap.xml generated by jekyll-sitemap plugin

### ISSUE THREAD

**Issue by AlanBarber** [jekyll/jekyll-archives#46]
I'm using archives to generate year, month, day files. This works fine but I noticed that the sitemap.xml that is generated by the jekyll-sitemap plugin doesn't include the generate files.

My _config.yml is as:
````
gems:
  - jekyll-archives 
  - jekyll-sitemap
````

**Comment by pathawks** [comment]
Can you explain a bit more about why you want the archive pages included in the sitemap?
As long as all of the posts are included, why would you need/want to include pages that only contain links to those posts?

**Comment by AlanBarber** [comment]
From my understanding of sitemaps you should list all pages on it so crawlers can optimize what to index. I would think having archive pages indexed would be useful as it might provide more content via the titles for searches to hit on your site.

**Comment by pathawks** [comment]
> From my understanding of sitemaps you should list all pages on it so crawlers can optimize what to index. 

All of my archive pages are `noindex`, so search engines can just avoid them. Ultimate optimization.

**Comment by AlanBarber** [comment]
I'm a .Net dev just starting to learn ruby, I'm working on understanding how Jekyll internally works but it looks like the archives plugin would need to be modified to insert entries into site.pages as that's what the sitemap plugin loops through.

**Comment by pathawks** [comment]
> it looks like the archives plugin would need to be modified to insert entries into site.pages as that's what the sitemap plugin loops through.

It would not be *difficult* to include archive pages in the sitemap; I’m just not convinced it would be a Good Idea.

It seems that most users would *not* want archive pages included in a sitemap, so the feature would probably need to be disabled by default. So we rework two plugins *and* add a new configuration option for what? What is the use case?

Archive pages have little to no content on their own. As long as the pages they link to are included in the sitemap, we do not need or want archive pages to be included.

**Comment by AlanBarber** [comment]
Let's ignore the sitemap issue at the moment since this is the archive plugin project after all.

On the [Jekyll Variables](http://jekyllrb.com/docs/variables/) page it lists that the site.pages is "A list of all Pages". I would think that anyone reading that would understand that to mean that if they look at the contents of the site.pages list they are getting an authoritative list of all pages that Jekyll has created for a site. 

As a plugin generating new pages, the correct thing to do it notify the Jekyll engine of the pages it has created. There are other processes, perhaps something Jekyll does or a 3rd party plugins that may want to perform actions on the entirety of pages that have been created. 

As a side note the sitemap plugin does not need any changes, and if anyone doesn't want archive pages to be shown in the sitemap then they should just need to add *sitemap: false* to the archive layout front matter to disable them.

**Comment by pathawks** [comment]
> On the Jekyll Variables page it lists that the site.pages is "A list of all Pages".

Yes, but `site.pages` does not contain all HTML files. A Jekyll [Page](http://jekyllrb.com/docs/pages/) is a specific type of thing, it does not include static HTML files or documents in a collections.

Some Jekyll sites will list all `site.pages` in a navigation somewhere on the site, it would be a Very Bad Idea to start including all archive pages in `site.pages`

> if anyone doesn't want archive pages to be shown in the sitemap then they should just need to add sitemap: false to the archive layout front matter to disable them.

Our job is to set defaults that are reasonable for most users, and *most users* would not want archive pages included in a sitemap. Therefore, [**jekyll-sitemap**](https://github.com/jekyll/jekyll-sitemap) would need to be modified to specifically exclude archive pages.

**Comment by AlanBarber** [comment]
Ok, I did my due diligence but looks like I won't be convincing you. Thanks for the discussion, it was fun.

**Comment by pathawks** [comment]
Thank *you* :smile:
