### ISSUE TITLE
Doesn't Work With gh-pages

### ISSUE THREAD

**Issue by jakebruemmer** [jekyll/jekyll-archives#60]
I'm not sure if this is by design, but this gem doesn't work with gh-pages anymore. I'd be willing to help try and fix it if I knew what the problem were.

Have there been any attempts to try and make it compatible?

Thanks

**Comment by parkr** [comment]
> this gem doesn't work with gh-pages anymore

This gem has never worked with GitHub Pages. For security reasons, GitHub Pages cannot run a plugin that has not been reviewed by GitHub's Security team.

To use custom plugins, [`@ixti`'s write-up from a couple years ago still works](http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html) – the gist is "generate locally and push the compiled `_site` to the Pages-compatible branch.

**Comment by jakebruemmer** [comment]
Ah -- didn't realize that it had never worked. I'll look at the post you linked. Thanks.

**Comment by miklb** [comment]
Is there a process to request a review by the GitHub security team or has it already been deemed "not safe"?

cc @benbalter

**Comment by benbalter** [comment]
@miklb it has not yet be reviewed, and could potentially be safe, but given competing priorities, we're focusing on higher-impact initiatives (e.g., Gem-based themes, HTTPS support) for the time being.

**Comment by gamb** [comment]
Damn. This is a bit of a show-stopper for me. Had just finished my site, but it depends heavily on jekyll-archives… @benbalter I guess there is no telling how long it might take for this package to undergo review?

**Comment by gamb** [comment]
Oh, I guess I'll compile locally for now. Not so bad…

**Comment by gamb** [comment]
For anyone hitting the same stub, using subtrees seems to work OK as a workflow.

Use at your own risk of course :-)…

```
SUBTREE_DIR=published/
jekyll build -d $SUBTREE_DIR
git add -A $SUBTREE_DIR
git commit -m "Auto-update: $(date)"
git subtree push --prefix=$SUBTREE_DIR origin gh-pages
```

**Comment by crpietschmann** [comment]
It'd be awesome if the Github team could revisit looking at the jekyll-archives plugin... This would be amazing to have access to with Jekyll!! Please!!

**Comment by miklb** [comment]
I think with GitHub Actions this will be moot. You’ll be able to run any plugin before deployment.

**Comment by crpietschmann** [comment]
@miklb Thats a great point! Hopefully GitHub Actions will help unlock some new possibilities. Also, I've been thinking about this and I think I may try to setting up an Azure DevOps Pipeline that builds a Jekyll site and see what the experience is there. :)

**Comment by miklb** [comment]
https://github.com/Azure/actions

:-D
