### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-archives#76]
Hey, @alfredxing! Think this is ready for a new release?

**Comment by alfredxing** [comment]
New gem version released! 🎉

**Comment by pathawks** [comment]
I wonder if it's about time to cut a new version. It looks like there have been [89 commits since `v1.0.0`](https://github.com/jekyll/jekyll-archives/compare/v1.0.0...master)

**Comment by parkr** [comment]
@pathawks Sure! 

I was thinking it'd be nice for @jekyllbot to cut an issue when we have > 20 or 30 commits sitting on master. It could be closed but just kind of a nice little reminder.

**Comment by pathawks** [comment]
> I was thinking it'd be nice for @jekyllbot to cut an issue when we have > 20 or 30 commits sitting on master.

Yes!

It would be nice if it were sophisticated enough to count PRs rather than commits, and exclude **dev** only PRs (like Rubocop stuff that doesn't change functionality)

**Comment by parkr** [comment]
> It would be nice if it were sophisticated enough to count PRs rather than commits, and exclude dev only PRs (like Rubocop stuff that doesn't change functionality)

Sounds like a simple GitHub Search query. 👍
