### ISSUE TITLE
Authors archive pages

### ISSUE THREAD

**Issue by yguezeldal** [jekyll/jekyll-archives#81]
When I look into blogpost meta data there is in most cases category, date, tags and **author**.

This gem is covering all except the last. I would like this gem to cover also archive pages for authors.

Do you think this is going over the scope of this gem?

**Comment by alfredxing** [comment]
AFAIK, Jekyll posts (documents) do not have `author` as a default attribute? It may be often added as a custom attribute but if it doesn't exist by default in Jekyll, I'm not sure if it would be a great idea to have in this plugin...

**Comment by yguezeldal** [comment]
Good point @alfredxing. Going along with jekyll defaults is a good way. Anyhow I think `author` could be a default in jekyll and hopefully this will trigger a discussion inside the core team.

**Comment by pathawks** [comment]
> Anyhow I think `author` could be a default in jekyll and hopefully this will trigger a discussion inside the core team.

What would that look like? How would that change things?

You think Jekyll should give all pages a `author: ""` by default? Should Jekyll enforce that all `author` are strings instead of an object (with email, avatar, Twitter username, etc)?

**Comment by yguezeldal** [comment]
I do not have a clear vision of how this could look like. the problem description is above. the solution is up for discussion.

**Comment by alfredxing** [comment]
@yguezeldal You should raise this as an issue in the main jekyll/jekyll repo if you think it should be a feature in Jekyll itself! It'll definitely get more discussion there.

Closing this for now.
