### ISSUE TITLE
How to get this working with Github Pages

### ISSUE THREAD

**Issue by martynchamberlin** [jekyll/jekyll-archives#83]
I truly wished that Github Pages allowed us to use this gem. I want to use both this and Github Pages badly and it gave me an idea. What if we had a way to locally build a static version of our site and then we pushed that static version to Github Pages and it did not build it as a Jekyll site but merely took those static HTML files and displayed them? 

The idea is fairly simple:

1. You write your Jekyll posts as normal, then push them to the master branch of your Github repo
2. This triggers a script on a service like CodeShip, CircleCI, or Travis. What the script does is it does a jekyll build of the site using this `jekyll-archives` gem and the domain as specified in your project's `CNAME` file. Then it pushes this static build as a commit to your `github-pages` branch of the repo. 

Assuming nothing like this already exists, I might build it.

**Comment by martynchamberlin** [comment]
All right, I've published a solution that's working for me. http://www.drinkingcaffeine.com/deploying-jekyll-to-github-pages-without-using-githubs-jekyll/ 

I don't know if there's a way to streamline this setup so users can have it with one click, but for those who are determined to get this working, it's really not hard now.

**Comment by alfredxing** [comment]
There isn't really anything we can do in this repository to fix this; GitHub decides which gems they want to include in GitHub Pages. The solution you mentioned would definitely be the way to go!

(Related: #60)

**Comment by kannansuresh** [comment]
Check this out [Automated Jekyll Archives for GitHub Pages](https://aneejian.com/automated-jekyll-archives-github-pages/).
