### ISSUE TITLE
Not possible to use front matter on created archive pages

### ISSUE THREAD

**Issue by salaroli** [jekyll/jekyll-archives#92]
Hi!

When creating the archives pages, I need a layout. My layout use front matter (like {{ page.image }}, {{ page.title }}, etc) but I can't find a way to use front matter with this plugin. I mean I can access the variables from the plugin, but I can't add any other

Could someone help me please?

Thanks!

**Comment by alfredxing** [comment]
I believe in Jekyll 3, page metadata is accessed in the layouts with the `layout` variable in Liquid. So your archive layout should use `{{ layout.image }}` instead of `{{ page.image }}`

More information: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata

Let me know if that works!

**Comment by intemperie** [comment]
It worked for me. Thanks!
