### ISSUE TITLE
Page titile, image, disscuss comment are not working on gh-pages

### ISSUE THREAD

**Issue by raghavendra990** [jekyll/jekyll-archives#95]
Hi all, 

I am using this theme [https://rohanchandra.github.io/type-theme/](https://rohanchandra.github.io/type-theme/) for my blog. In my local computer when I am doing `jekyll serve ` everything looks normal but when I see the same code on gh-pages [http://raghavendra990.github.io/](http://raghavendra990.github.io/). it completely different. 

Please guide, what is the issue?

**Comment by missmatsuko** [comment]
GitHub pages only allows certain plugins. This is not one of them.
